import Link from "next/link";
import { notFound } from "next/navigation";
import { format } from "date-fns";
import { prisma } from "@/lib/db/prisma";
import { requireUser } from "@/lib/auth/session";
import { isServerAdmin } from "@/domains/server/server-admin";
import { createServerCollection, deleteServerCollection, removeCollectionMembership, setCollectionMembership, toggleServerCollectionArchive, transferCollectionOwnership, updateServerCollection } from "@/domains/server/actions";
import { collectionRoleDescriptions, collectionRoleLabels } from "@/domains/auth/permissions";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input, Select, Textarea } from "@/components/ui/input";
import { CreatePanel } from "@/components/forms/CreatePanel";
import { formatBytes } from "@/domains/server/server-metrics";

export const dynamic = "force-dynamic";
const roles = ["COLLECTION_OWNER", "AQUARIST", "FISHKEEPER", "VIEWER"] as const;

export default async function ServerCollectionsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const actor = await requireUser(); if (!(await isServerAdmin(actor))) notFound();
  const params = await searchParams; const q = params.q?.trim();
  const collections = await prisma.collection.findMany({ where: { ...(q ? { name: { contains: q, mode: "insensitive" as const } } : {}), ...(params.status === "active" ? { archivedAt: null } : params.status === "archived" ? { archivedAt: { not: null } } : {}) }, include: { owner: true, memberships: { include: { user: true }, orderBy: { role: "asc" } }, storageEstimates: { orderBy: { measuredAt: "desc" }, take: 1 }, _count: { select: { aquariums: true, items: true, mediaAssets: true } } }, orderBy: { name: "asc" } });
  return <div className="space-y-6"><PageHeader title="Collection Management" eyebrow="Server administration"><Link href="/server-maintenance" className="text-sm font-semibold text-primary underline">Back to maintenance</Link></PageHeader>
    <Card><CardContent className="p-4"><form className="grid gap-3 sm:grid-cols-[1fr_11rem_auto]"><Input name="q" defaultValue={q ?? ""} placeholder="Search collections" /><Select name="status" defaultValue={params.status ?? "all"}><option value="all">All collections</option><option value="active">Active</option><option value="archived">Archived</option></Select><Button type="submit" variant="secondary">Filter</Button></form></CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-[1fr_390px]"><section className="space-y-4">{collections.map((collection) => { const ownerCount = collection.memberships.filter((membership) => membership.role === "COLLECTION_OWNER").length; const primaryOwnerMembership = collection.memberships.some((membership) => membership.userId === collection.ownerId && membership.role === "COLLECTION_OWNER"); return <Card key={collection.id}><CardContent className="space-y-5 p-5">
      <div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold text-primary">{collection.name}</h2><p className="text-sm text-muted-foreground">Primary owner: {collection.owner.name} · {collection.owner.email}</p><p className="text-xs text-muted-foreground">Created {format(collection.createdAt, "MMM d, yyyy")}</p></div><Badge>{collection.archivedAt ? "Archived" : "Active"}</Badge></div>
      <div className="grid gap-3 sm:grid-cols-5"><Stat label="Members" value={collection.memberships.length} /><Stat label="Aquariums" value={collection._count.aquariums} /><Stat label="Inventory" value={collection._count.items} /><Stat label="Photos" value={collection._count.mediaAssets} /><Stat label="Storage" value={formatBytes(Number(collection.storageEstimates[0]?.uploadBytes ?? 0))} /></div>
      <div className={`rounded-md border p-3 text-sm ${ownerCount > 0 && primaryOwnerMembership ? "border-green-300 bg-green-50 text-green-900 dark:border-green-900 dark:bg-green-950/20 dark:text-green-100" : "border-red-300 bg-red-50 text-red-900 dark:border-red-900 dark:bg-red-950/20 dark:text-red-100"}`}>Integrity: {ownerCount > 0 && primaryOwnerMembership ? `${ownerCount} Collection Owner membership(s); primary owner is consistent.` : "Owner membership requires repair."}</div>
      <details className="rounded-md border border-border p-3"><summary className="cursor-pointer font-semibold text-primary">Edit collection</summary><form action={updateServerCollection} className="mt-3 grid gap-3"><input type="hidden" name="id" value={collection.id} /><Input name="name" defaultValue={collection.name} required /><Textarea name="description" defaultValue={collection.description ?? ""} /><Button type="submit" className="w-fit">Save collection</Button></form></details>
      <div><h3 className="font-semibold text-primary">Memberships</h3><div className="mt-2 space-y-2">{collection.memberships.map((membership) => <div key={membership.id} className="grid gap-3 rounded-md bg-muted/45 p-3 text-sm lg:grid-cols-[1fr_auto_auto] lg:items-center"><span><strong>{membership.user.name}</strong> · {membership.user.email}<span className="block text-xs text-muted-foreground">{collectionRoleDescriptions[membership.role]}</span></span><Badge>{collectionRoleLabels[membership.role]}</Badge><form action={removeCollectionMembership}><input type="hidden" name="id" value={membership.id} /><Button type="submit" variant="secondary" disabled={membership.userId === collection.ownerId || (membership.role === "COLLECTION_OWNER" && ownerCount <= 1)}>Remove</Button></form></div>)}</div>
        <form action={setCollectionMembership} className="mt-3 grid gap-3 sm:grid-cols-[1fr_12rem_auto]"><input type="hidden" name="collectionId" value={collection.id} /><Input name="email" type="email" placeholder="Existing user email" required /><Select name="role" defaultValue="VIEWER">{roles.map((role) => <option key={role} value={role}>{collectionRoleLabels[role]}</option>)}</Select><Button type="submit">Add / update</Button></form>
      </div>
      <details className="rounded-md border border-border p-3"><summary className="cursor-pointer font-semibold text-primary">Transfer primary ownership</summary><form action={transferCollectionOwnership} className="mt-3 flex flex-col gap-3 sm:flex-row"><input type="hidden" name="collectionId" value={collection.id} /><Input name="email" type="email" placeholder="New owner email" required /><Button type="submit">Transfer ownership</Button></form></details>
      <div className="flex flex-wrap gap-2"><form action={toggleServerCollectionArchive}><input type="hidden" name="id" value={collection.id} /><Button type="submit" variant="secondary">{collection.archivedAt ? "Restore collection" : "Archive collection"}</Button></form></div>
      <details className="rounded-md border border-red-300 bg-red-50/70 p-3 dark:border-red-900 dark:bg-red-950/20"><summary className="cursor-pointer text-sm font-semibold text-red-800 dark:text-red-200">Delete collection permanently</summary><p className="mt-2 text-xs text-muted-foreground">This permanently deletes all aquariums, inventory, schedules, events, and media records scoped to this collection.</p><form action={deleteServerCollection} className="mt-3 flex flex-col gap-2 sm:flex-row"><input type="hidden" name="id" value={collection.id} /><Input name="confirmation" placeholder={`Type DELETE ${collection.name}`} required /><Button type="submit" variant="secondary">Delete permanently</Button></form></details>
    </CardContent></Card>; })}</section>
      <CreatePanel title="Create collection"><form action={createServerCollection} className="grid gap-3"><label className="grid gap-1"><span className="text-sm font-medium">Collection name</span><Input name="name" required /></label><label className="grid gap-1"><span className="text-sm font-medium">Primary owner email</span><Input name="ownerEmail" type="email" required /></label><label className="grid gap-1"><span className="text-sm font-medium">Description</span><Textarea name="description" /></label><Button type="submit">Create collection</Button></form></CreatePanel>
    </div>
  </div>;
}
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="rounded-md bg-muted/45 p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="font-mono font-semibold text-primary">{value}</div></div>; }
