import { stat, readFile } from "fs/promises";
import { prisma } from "@/lib/db/prisma";
import { writeAuditLog } from "@/domains/audit/audit-log";
import { generateTankCoverImage, moderateImage } from "@/domains/ai/ai-service";
import { createImageThumbnail, detectImageType, imageDimensions, localMediaPath } from "@/domains/media/media-service";
import { formatAdditionalContentsForEddy } from "@/domains/aquariums/additional-contents";
import type { AquariumCoverPayload } from "@/domains/ai-jobs/types";
import { recordAiJobEvent } from "@/domains/ai-jobs/events";

export async function executeAiCoverImageForJob(collectionId: string, userId: string, options: AquariumCoverPayload, jobId: string, attemptNumber: number) {
  const aquarium = await prisma.aquarium.findFirstOrThrow({ where: { id: options.aquariumId, collectionId }, include: { profile: true, items: { where: { status: "ACTIVE" }, orderBy: { updatedAt: "desc" } }, additionalContents: { where: { archivedAt: null, includeInEddyContext: true }, orderBy: [{ category: "asc" }, { createdAt: "asc" }] }, readings: { orderBy: { measuredAt: "desc" }, take: 8 }, events: { orderBy: { eventDate: "desc" }, take: 6 } } });
  const cover = await generateTankCoverImage({ collectionId, aquariumId: aquarium.id, userId, name: aquarium.name, volumeGallons: aquarium.volumeGallons, tankType: `${aquarium.salinity} ${aquarium.aquariumType}`, stocking: aquarium.items.filter((item) => ["FISH", "INVERT"].includes(item.itemType)).map((item) => item.name), plants: aquarium.items.filter((item) => item.itemType === "PLANT").map((item) => item.name), additionalContents: formatAdditionalContentsForEddy(aquarium.additionalContents).split("\n").filter(Boolean), hardscape: aquarium.items.filter((item) => item.itemType === "HARDSCAPE").map((item) => item.name), substrate: aquarium.profile?.substrate, lighting: aquarium.profile?.lightingType, selectedConceptTitle: options.selectedConceptTitle, selectedConceptPrompt: options.selectedConceptPrompt, selectedConceptDescription: options.selectedConceptDescription, selectedConceptTags: options.selectedConceptTags, customPrompt: options.customPrompt, vibeNotes: options.selectedConceptPrompt ?? options.customPrompt ?? aquarium.profile?.notes ?? aquarium.notes, latestParameters: aquarium.readings.map((reading) => ({ parameter: reading.parameter, value: reading.value, unit: reading.unit })), recentEvents: aquarium.events.map((event) => ({ eventType: event.eventType, title: event.title, summary: event.summary })) });
  if (!cover.url) throw new Error("Eddy generated no cover image URL.");
  await prisma.aiJob.update({ where: { id: jobId }, data: { progress: 60, progressMessage: "Image received" } });
  await recordAiJobEvent(prisma, { jobId, eventType: "PROVIDER_RESPONSE_RECEIVED", message: "Image response received", statusSnapshot: "RUNNING", attemptNumber, metadata: { provider: process.env.AI_PROVIDER || "mock", model: cover.model, providerRequestId: cover.providerRequestId, endpoint: cover.endpoint, size: cover.size, quality: cover.quality } });
  const [buffer, info] = await Promise.all([readFile(localMediaPath(cover.url)), stat(localMediaPath(cover.url))]);
  const mimeType = detectImageType(buffer); if (!mimeType) throw new Error("Eddy cover image could not be read as PNG, JPEG, or WebP.");
  const moderation = await moderateImage({ dataUrl: `data:${mimeType};base64,${buffer.toString("base64")}`, filename: cover.filename, collectionId, userId, entityType: "Aquarium", entityId: aquarium.id });
  if (moderation.blocked) throw new Error(moderation.reason || "The generated cover image was blocked by moderation.");
  const dimensions = imageDimensions(buffer, mimeType);
  const thumbnailUrl = await createImageThumbnail({ buffer, aquariumId: aquarium.id, sourceFilename: cover.filename }).catch(() => null);
  const media = await prisma.mediaAsset.create({ data: { collectionId, aquariumId: aquarium.id, uploadedById: userId, filename: cover.filename, originalFilename: cover.filename, mimeType, sizeBytes: Number(info.size), width: dimensions.width, height: dimensions.height, url: cover.url, thumbnailUrl, caption: options.selectedConceptTitle ? `Eddy cover: ${options.selectedConceptTitle}` : "Eddy-generated aquarium cover", altText: `Eddy-generated cover image for ${aquarium.name}`, mediaSource: "AI_GENERATED", moderationStatus: moderation.flagged ? "FLAGGED" : "APPROVED", moderationReason: moderation.reason ?? null, moderationModel: process.env.OPENAI_MODERATION_MODEL || null, moderationCheckedAt: new Date(), moderationAttempts: 1 } });
  await prisma.aiJob.update({ where: { id: jobId }, data: { progress: 75, progressMessage: "Saved to media library" } });
  await recordAiJobEvent(prisma, { jobId, eventType: "MEDIA_SAVED", message: "Saved to media library", statusSnapshot: "RUNNING", attemptNumber, metadata: { mediaId: media.id, imageUrl: media.url, mimeType, width: dimensions.width, height: dimensions.height, sizeBytes: Number(info.size) } });
  await prisma.aiJob.update({ where: { id: jobId }, data: { progress: 85, progressMessage: media.moderationStatus === "APPROVED" ? "Moderation approved" : "Moderation needs review" } });
  await recordAiJobEvent(prisma, { jobId, eventType: "MODERATION_COMPLETED", message: media.moderationStatus === "APPROVED" ? "Moderation approved" : "Moderation requires review", statusSnapshot: "RUNNING", attemptNumber, metadata: { mediaId: media.id, moderationStatus: media.moderationStatus, moderationModel: media.moderationModel } });
  if (media.moderationStatus !== "APPROVED") throw new Error(moderation.reason || "The generated cover image needs review before it can be used as a cover.");
  const assigned = options.setAsCover !== false && (await prisma.aquarium.updateMany({ where: { id: aquarium.id, collectionId, coverMediaAssetId: options.expectedCoverMediaAssetId ?? null }, data: { coverImageUrl: cover.url, coverMediaAssetId: media.id } })).count === 1;
  await prisma.aiJob.update({ where: { id: jobId }, data: { progress: 95, progressMessage: assigned ? "Applied as aquarium cover" : "Image saved; newer cover preserved" } });
  await recordAiJobEvent(prisma, { jobId, eventType: assigned ? "COVER_ASSIGNED" : "COVER_ASSIGNMENT_SKIPPED", message: assigned ? "Applied as aquarium cover" : "Image generated, but the aquarium cover changed before completion", statusSnapshot: "RUNNING", attemptNumber, metadata: { aquariumId: aquarium.id, mediaId: media.id, assignedAsCover: assigned } });
  await prisma.aiSuggestion.create({ data: { aquariumId: aquarium.id, suggestionType: "COVER_CARD", prompt: cover.prompt, response: { ...cover, mediaAssetId: media.id, selectedConceptId: options.selectedConceptId ?? null, selectedConceptTitle: options.selectedConceptTitle ?? null, assignedAsCover: assigned } as never, selected: assigned } });
  await writeAuditLog({ collectionId, entityType: "MediaAsset", entityId: media.id, action: "AI_COVER_IMAGE_APPROVED", after: { aquariumId: aquarium.id, url: cover.url, selectedConceptId: options.selectedConceptId ?? null }, createdById: userId });
  await writeAuditLog({ collectionId, entityType: "Aquarium", entityId: aquarium.id, action: "GENERATE_AI_COVER_IMAGE", after: { ...cover, mediaAssetId: media.id, selectedConceptId: options.selectedConceptId ?? null, assignedAsCover: assigned }, createdById: userId });
  return { mediaId: media.id, imageUrl: cover.url, assignedAsCover: assigned, moderationStatus: media.moderationStatus };
}
