"use client";

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";

type Device = { id: string; endpoint: string; deviceLabel: string | null; userAgent: string | null; enabled: boolean; createdAt: string; lastSeenAt: string | null };

function keyBytes(value: string) { const raw = atob((value + "=".repeat((4 - value.length % 4) % 4)).replace(/-/g, "+").replace(/_/g, "/")); return Uint8Array.from(raw, (character) => character.charCodeAt(0)); }
function deviceName(userAgent?: string | null) { if (/iphone|ipad/i.test(userAgent || "")) return "iPhone or iPad PWA"; if (/android/i.test(userAgent || "")) return "Android browser"; if (/mac/i.test(userAgent || "")) return "Mac browser"; if (/windows/i.test(userAgent || "")) return "Windows browser"; return "Browser device"; }

export function PushNotificationSettings({ enabled, publicKey, devices }: { enabled: boolean; publicKey: string; devices: Device[] }) {
  const [supported, setSupported] = useState(false); const [permission, setPermission] = useState<NotificationPermission>("default"); const [endpoint, setEndpoint] = useState<string | null>(null); const [items, setItems] = useState(devices); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const currentEnabled = useMemo(() => items.some((item) => item.enabled && item.endpoint === endpoint), [items, endpoint]);
  useEffect(() => { const support = "serviceWorker" in navigator && "PushManager" in window && "Notification" in window; setSupported(support); if ("Notification" in window) setPermission(Notification.permission); if (!support) return; navigator.serviceWorker.register("/sw.js").then((registration) => registration.pushManager.getSubscription()).then((subscription) => { setEndpoint(subscription?.endpoint || null); if (subscription?.endpoint) fetch("/api/push-subscriptions", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ endpoint: subscription.endpoint }) }).catch(() => undefined); }).catch(() => setMessage("Fluxpoint could not register notifications in this browser.")); }, []);
  async function enablePush() { setBusy(true); setMessage(""); try { if (!enabled || !publicKey) throw new Error("Web Push is not enabled on this server."); if (!supported) throw new Error("This browser does not support Web Push notifications."); if (!window.isSecureContext) throw new Error("Web Push requires HTTPS, except on localhost."); const next = await Notification.requestPermission(); setPermission(next); if (next !== "granted") throw new Error("Notification permission was not granted."); const registration = await navigator.serviceWorker.register("/sw.js"); const subscription = await registration.pushManager.getSubscription() || await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: keyBytes(publicKey) }); const response = await fetch("/api/push-subscriptions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(subscription.toJSON()) }); if (!response.ok) throw new Error("Fluxpoint could not save this device."); const result = await response.json(); setEndpoint(subscription.endpoint); setItems((current) => [{ ...result.subscription, userAgent: navigator.userAgent, createdAt: new Date().toISOString(), lastSeenAt: new Date().toISOString() }, ...current.filter((item) => item.endpoint !== subscription.endpoint)]); setMessage("Push notifications are enabled for this browser."); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  async function revoke(device: Device) { setBusy(true); setMessage(""); try { await fetch("/api/push-subscriptions", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: device.id }) }); if (device.endpoint === endpoint) { const registration = await navigator.serviceWorker.getRegistration(); const subscription = await registration?.pushManager.getSubscription(); await subscription?.unsubscribe(); setEndpoint(null); } setItems((current) => current.filter((item) => item.id !== device.id)); setMessage("Push device revoked."); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  async function testPush() { setBusy(true); setMessage(""); try { const response = await fetch("/api/push-subscriptions/test", { method: "POST" }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Fluxpoint could not send a test push."); setMessage(result.sent > 0 ? "Test push sent." : "No enabled device accepted the test push."); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  return <div className="grid gap-4"><div className="rounded-md bg-muted/45 p-3 text-sm"><p>Browser support: {supported ? "supported" : "not supported"}</p><p>Permission: {permission === "default" ? "not requested" : permission}</p>{!enabled && <p className="mt-2 text-amber-700 dark:text-amber-300">Web Push is disabled on this server.</p>}{!supported && <p className="mt-2 text-muted-foreground">You can continue using Fluxpoint normally without push notifications.</p>}<p className="mt-2 text-muted-foreground">On iPhone and iPad, add Fluxpoint to the Home Screen before enabling push.</p></div><div className="flex flex-wrap gap-2"><Button type="button" onClick={enablePush} disabled={busy || currentEnabled}>Enable this device</Button><Button type="button" variant="secondary" onClick={testPush} disabled={busy || !currentEnabled}>Send test push</Button></div>{message && <p className="rounded-md border border-border p-3 text-sm">{message}</p>}<div className="grid gap-2"><h4 className="font-semibold">Registered devices</h4>{items.length ? items.map((device) => <div key={device.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-border p-3 text-sm"><div><div className="font-semibold">{device.deviceLabel || deviceName(device.userAgent)}</div><div className="text-xs text-muted-foreground">{device.lastSeenAt ? `Last seen ${new Date(device.lastSeenAt).toLocaleString()}` : "Not seen yet"}</div></div><Button type="button" variant="secondary" onClick={() => revoke(device)} disabled={busy}>Revoke</Button></div>) : <p className="text-sm text-muted-foreground">No push devices are registered.</p>}</div></div>;
}
