export type MediaAssetView = {
  id: string;
  url: string;
  thumbnailUrl: string | null;
  caption: string | null;
  description?: string | null;
  photographer?: string | null;
  captureDate?: Date | null;
  tags?: unknown;
  mediaSource?: "USER_UPLOAD" | "AI_GENERATED" | "IMPORTED" | "OTHER";
  altText: string | null;
  moderationStatus: "PENDING" | "APPROVED" | "FLAGGED" | "REJECTED" | "ERROR";
  hiddenAt: Date | null;
  createdAt: Date;
  updatedAt?: Date;
  originalFilename?: string;
  filename?: string;
  sizeBytes?: number;
  width?: number | null;
  height?: number | null;
  uploadedBy?: { name: string | null; email: string | null } | null;
  speciesDefinition?: { id: string; commonName: string; scientificName: string | null } | null;
  speciesVariant?: { id: string; displayName: string | null; name: string } | null;
  speciesLinks?: Array<{
    id: string;
    speciesDefinition: { id: string; commonName: string; scientificName: string | null };
    speciesVariant?: { id: string; displayName: string | null; name: string } | null;
  }>;
  item?: { name: string; itemType: string } | null;
  aquariumEvent?: { title: string; eventDate: Date } | null;
};
